name: Deploy to Cloudflare Pages

on:
  schedule:
    - cron: "0 3 * * *"  # 每天 UTC 时间 03:00 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to Cloudflare Pages
        run: |
          curl -X POST "https://api.cloudflare.com/client/v4/pages/projects/YOUR_PROJECT/deployments" \
          -H "Authorization: Bearer ${{ secrets.CF_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          --data '{}'
